import { getUserCreds, validateUser, welComeScreen, startProgram } from "./helper.js";
import { getBalance } from '../Repos/accounting.js';
await welComeScreen('A T M . CLI');
await getUserCreds();
await validateUser();
await getBalance();
//await getStatement();
//await balanceEnqiry();
//await atmOptions();
await startProgram();
//await getStatement();
